---
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports
      exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    - id: add-trailing-comma
      exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    - id: autopep8
      exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
      additional_dependencies: [types-all]
